---
driver:
  name: ec2
  region: us-east-1
  subnet_id: subnet-76a1123d
  require_chef_omnibus: true
  instance_type: t3.small
  associate_public_ip: true

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.12.9

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: bake
    run_list:
      - role[bake]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: full
    run_list:
      - role[full]
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/full
    attributes:
