---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: centos-7

suites:
  - name: bake
    run_list:
      - role[bake]
    attributes:
  - name: full
    run_list:
      - role[full]
    attributes:
